### ISSUE TITLE
Dormitory Objekt erzeugen

### ISSUE THREAD

**Issue by sgeisler** [sgeisler/test-redmine-issue-migration#166]
---

Author Name: **jacobs** (jacobs)
Original Redmine Issue: 196, http://projecthost.wh2.tu-dresden.de/redmine/issues/196
Original Date: 2012/01/22
Original Assignee: mmarx

---

Beim Versuch ein Dormitory Objekt zu erzeugen kommt es zu einer komplexen Fehlermeldung

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Volumes/Data/Projekte/agdsn/datenbank/Pycroft/console/console.py", line 38, in newDorm
    street=street)
  File "<string>", line 2, in __init__
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/instrumentation.py", line 309, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/langhelpers.py", line 484, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/instrumentation.py", line 157, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Library/Python/2.7/site-packages/sqlalchemy/event.py", line 274, in __call__
    fn(*args, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/mapper.py", line 2936, in _event_on_first_init
    configure_mappers()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/mapper.py", line 2861, in configure_mappers
    mapper._post_configure_properties()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/mapper.py", line 1166, in _post_configure_properties
    prop.init()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/interfaces.py", line 128, in init
    self.do_init()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/properties.py", line 919, in do_init
    self._generate_backref()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/properties.py", line 1418, in _generate_backref
    mapper._configure_property(backref_key, relationship)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/mapper.py", line 1145, in _configure_property
    prop.init()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/interfaces.py", line 128, in init
    self.do_init()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/properties.py", line 913, in do_init
    self._process_dependent_arguments()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/properties.py", line 969, in _process_dependent_arguments
    setattr(self, attr, attr_value())
TypeError: id() takes exactly one argument (0 given)

**Comment by sgeisler** [comment]
---

Original Redmine Comment
Author Name: **mmarx** (mmarx)
Original Date: 2012/01/28 16:49:39 +0100

---

Fixed-by: commit:7fdcb526, commit:7f72d17a.
